dado = input('Digite algo: ')
print('O tipo primitivo desse dado é', type(dado))
print('Só tem espaço?', dado.isspace())
print(f'É um número?', dado.isalnum())
print('É alfabético?', dado.isalpha())
print('Está em maiúsculo?', dado.isupper())
print('Está em minúsculo?', dado.islower())
print('Está capitalizado?', dado.istitle())
print('É imprimível?', dado.isprintable())

a = input('Digite algo: ')

print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços?:', 'Sim.' if a.isspace() else 'Não.')
print('É um numero?:', 'Sim.' if a.isnumeric() else 'Não.')
print('É um alfabético?:', 'Sim.' if a.isalpha() else 'Não.')
print('É um alfanumérico?:', 'Sim.' if a.isalnum() else 'Não.')
print('Está em maiúsculo?:', 'Sim.' if a.isupper() else 'Não.')
print('Está em minúsculo?: ', 'Sim.' if a.islower() else 'Não.')
print('Está capitalizada?:', 'Sim.' if a.istitle() else 'Não.')